### ISSUE TITLE
I hope you can make 2K

### ISSUE THREAD

**Issue by sanyuede** [kratosator/apex-legends-obs-game#1]
My 2K screen with 1080 resolution will be very blurred. I hope you can make 2K. Thank you

**Comment by kratosator** [comment]
Sure, I can make it. supporting multiple game resolutions is something I was planning to do.
I'll add support for the game on a 2k screen.

If you have OBS configured to output a 1080p video signal you can try a temporary work around. Add your Apex Legends game source in a dedicated scene and add the filter on that scene. You can then add the scene as a source in all your other scenes.
However, I can't guarrantee that everything will work because of the resize made by OBS, it could break the reconition of HUD items.

**Comment by sanyuede** [comment]
> Sure, I can make it. supporting multiple game resolutions is something I was planning to do. I'll add support for the game on a 2k screen.
> 
> If you have OBS configured to output a 1080p video signal you can try a temporary work around. Add your Apex Legends game source in a dedicated scene and add the filter on that scene. You can then add the scene as a source in all your other scenes. However, I can't guarrantee that everything will work because of the resize made by OBS, it could break the reconition of HUD items.

Can I add your chat friend

**Comment by kratosator** [comment]
If you want you can write to me on Discord, kratosator#4822

**Comment by kratosator** [comment]
@sanyuede I've almost completed the support for 2k, I need to do some checks and minor tweaks.
Hopefully, in the next weekend I'll finish and release a new version.

**Comment by kratosator** [comment]
Support to 2k display has been implemented in version 1.4.0.
